### PR TITLE
s/celcius/celsius/g

### PR DESCRIPTION
**Pull request by dmpayton**
As pointed out by @stephengtuggy. 🤦‍♂️

### CODE REVIEW

**Review by stephengtuggy — COMMENTED** [review]
Much better.

Did the incorrect spelling make it into the database? Is a migration needed?

**Comment by dmpayton** [comment]
Yep, I had the migration but forgot to include it in the commit. 👍🏻

**Review by stephengtuggy — APPROVED** [review]
Looks good to me!

**Comment by alexandermccormick** [comment]
This made my day

**Pull request merged**
